name: func_test
run-name: Functional testing

on: workflow_dispatch
  
jobs:
  # "Process compelted with exit code 1" error for windows
  # - Permission issues on GitHub actions or something else?
  # - This seems to work just fine on a standard local Windows machine
  # amd64_windows:
  #   name: AMD64 Windows
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build
  #     shell: powershell
  #     run: |
  #       set RUST_BACKTRACE=1
  #       set CARGO_NET_GIT_FETCH_WITH_CLI=true
  #       set CARGO_NET_RETRY=10
  #       Set-ExecutionPolicy Unrestricted
  #       cargo test --manifest-path app/entrusted_client/Cargo.toml
  # TODO review macos to use Docker in /Applications folder with Docker Desktop  
  amd64_macos:
    name: AMD64 Mac OS
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: bash
      run: |
        brew install lima
        limactl start
        CARGO_NET_GIT_FETCH_WITH_CLI=true CARGO_NET_RETRY=10 cargo test --manifest-path app/entrusted_client/Cargo.toml
  amd64_linux:
    name: AMD64 Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: bash
      run: |
        CARGO_NET_GIT_FETCH_WITH_CLI=true CARGO_NET_RETRY=10 cargo test --manifest-path app/entrusted_client/Cargo.toml
